### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by justanotheranonymoususer**
https://github.com/x64dbg/x64dbg.github.io/issues/6

### CODE REVIEW

**Comment by mrexodia** [comment]
Hi,

I'll accept this pull request when a new release version is coming out. Currently the latest release uses MSVC2010 :)

**Comment by justanotheranonymoususer** [comment]
Well, perhaps it's a good time for a new version ☺

**Comment by mrexodia** [comment]
Yes, but there are quite some unfinished things in the snapshot. Various
crash bugs, unfinished script api, things like that.

**Comment by mrexodia** [comment]
was done manually. thanks for the pull request!

**Pull request closed without merging**
